# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cldkctl < Formula
  desc "A CLI tool for managing cloud infrastructure"
  homepage "https://github.com/wildanmr/cldkctl"
  version "0.0.9-DEVELOPMENT"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.9-DEVELOPMENT/cldkctl-0.0.9-DEVELOPMENT_Darwin_x86_64.tar.gz"
      sha256 "1f9178d9367419e18346d4f9696629009f47423c55764990a963ebe1ef4826e2"

      def install
        bin.install "cldkctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.9-DEVELOPMENT/cldkctl-0.0.9-DEVELOPMENT_Darwin_arm64.tar.gz"
      sha256 "e53a96a0145a98310535c9f629275d8a4cedac99c92bfc53141b71c7ee08a0c1"

      def install
        bin.install "cldkctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.9-DEVELOPMENT/cldkctl-0.0.9-DEVELOPMENT_Linux_x86_64.tar.gz"
        sha256 "5110c4144d1a3f64e81170c29a58d26c266d8254b44421cc0e8994455fa0a065"

        def install
          bin.install "cldkctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.9-DEVELOPMENT/cldkctl-0.0.9-DEVELOPMENT_Linux_arm64.tar.gz"
        sha256 "53aaae99f0d6257792633d9d82a89358484bb1bf73c2d23c535602771352a856"

        def install
          bin.install "cldkctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cldkctl --version"
  end
end
