# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cldkctl < Formula
  desc "A CLI tool for managing cloud infrastructure"
  homepage "https://github.com/wildanmr/cldkctl"
  version "0.0.11-DEVELOPMENT"
  license "MIT"

  depends_on "go"
  depends_on "yq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.11-DEVELOPMENT/cldkctl-0.0.11-DEVELOPMENT_Darwin_x86_64.tar.gz"
      sha256 "8eca7991de0bc0b8ee763d314259c0b6bcaf2c28274fa008a17ced4775ed5c1f"

      def install
        bin.install "cldkctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.11-DEVELOPMENT/cldkctl-0.0.11-DEVELOPMENT_Darwin_arm64.tar.gz"
      sha256 "3ca511cfbdd7797402e947afbb76cc69110d2c8c1bc6e192653dc9d9c4cf69af"

      def install
        bin.install "cldkctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.11-DEVELOPMENT/cldkctl-0.0.11-DEVELOPMENT_Linux_x86_64.tar.gz"
        sha256 "07e749723394708e858cc2eef46bfdc6b4ef0422da3c6465c0462b748ece6d31"

        def install
          bin.install "cldkctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wildanmr/cldkctl/releases/download/v0.0.11-DEVELOPMENT/cldkctl-0.0.11-DEVELOPMENT_Linux_arm64.tar.gz"
        sha256 "b7c1878c46b4714c0f52ae7cf69117cd404763a797eb4fabf800088373d947a5"

        def install
          bin.install "cldkctl"
        end
      end
    end
  end

  test do
    system "#{bin}/cldkctl --version"
  end
end
